version: "3.0"
services:
  nginx:
    container_name: nginx
    image: test/nginx:v2
    ports:
      - "1078:1078"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default.conf:/etc/nginx/sites-enabled/default
      - ./nginx/logs:/var/log/nginx
      - ./backend/public:/var/www/app/public
      - ./frontend/public/favicon.ico:/home/favicon.ico
    depends_on:
      - frontend
      - backend
    networks:
      default:
        aliases:
          - network
  redis:
    container_name: redis
    image: test/redis:latest
    ports:
      - "6379"
    networks:
      default:
        aliases:
          - network
  backend:
    image: backend:latest
    container_name: backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=08aJvg2zwPNl3fhQgRlX1jidvSLxDuCn
      - MYSQL_DATABASE_NAME=postgres
      - TYPEORM_SYNCHRONIZE=true
      - JWT_SECRET_KEY=1cc5423785942719eb714dab5f2eba37b0c858aed0aeaec255008b456e8a3cb7
      - JWT_EXPIRES_IN=90000s
      - JWT_REFRESH_EXPIRES_IN=2592000
      - PORT=5656
      - GRAYLOG_ENABLE=true
      - GRAYLOG_HOST=graylog
      - GRAYLOG_PORT=12201
      - GRAYLOG_HOSTNAME=localhost
      - MAIL_HOST=smtp.mandrillapp.com
      - MAIL_PORT=465
      - MAIL_SECURE=true
      - MAIL_USER=yetkinlik@a.com
      - MAIL_PASS=gKno-16HZDNYUwWC7uiJMw
      - MAIL_FROM=demo@mustafa.net
      - MAIL_PREVIEW=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

    ports:
      - "5656"
    depends_on:
      - mysql
    networks:
      default:
        aliases:
          - network
  mysql:
    image: local/mysql8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=08aJvg2zwPNl3fhQgRlX1jidvSLxDuCn
      - TZ=Europe/Istanbul  # Set the timezone to Istanbul
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3388:3306"
    #command: bash -c "docker-entrypoint.sh --datadir=/var/lib/mysql --socket=/var/run/mysqld/mysqld.sock --pid-file=/var/run/mysqld/mysqld.pid --sql-mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'"
    networks:
      default:
        aliases:
          - network
  frontend:
    image: local/local:latest
    container_name: frontend
    environment:
      NEXT_PUBLIC_PROJECT_ID: "c622qN-3FNHfK-uiPBzQ"
      #PORT: 3000 Geçici olarak kapatıldı. Refine port ile çalışacağı zaman aktif edilecek
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - ./frontend/public:/app/public
    ports:
      - "3000"
    networks:
      default:
        aliases:
          - network
    depends_on:
      - backend
